import { useEffect, useState } from "react";
import { Filter, Search, Wrench } from "lucide-react";
import { getRequests } from "../api";
import type { RequestItem } from "../types";

const demo: RequestItem[] = [
 {req_uid:"TMS/SUR/1001",dept:"Engineering",asset_id:"TRK-041",block_section_id:"BS-JP-AII-04",section_id:"JP-AII",activity_code:"TRK-INS",activity_desc:"Track geometry inspection",dept_priority_code:"P1",dept_priority_rank:1,days_overdue:4,safety_critical_flag:1,requested_duration_min:120,min_viable_duration_min:90,earliest_start_date:"2026-09-15",latest_finish_date:"2026-09-20",request_status:"PENDING",joint_dept_required:null},
 {req_uid:"SMMS/SUR/2001",dept:"S&T",asset_id:"SIG-014",block_section_id:"BS-JP-AII-04",section_id:"JP-AII",activity_code:"CBL-LAY",activity_desc:"Signalling cable rectification",dept_priority_code:"B2",dept_priority_rank:4,days_overdue:0,safety_critical_flag:0,requested_duration_min:180,min_viable_duration_min:120,earliest_start_date:"2026-09-15",latest_finish_date:"2026-10-30",request_status:"PENDING",joint_dept_required:"ENGG"},
 {req_uid:"TDMS/SUR/3007",dept:"TRD",asset_id:"OHE-022",block_section_id:"BS-AII-REW-07",section_id:"AII-REW",activity_code:"OHE-INS",activity_desc:"OHE insulator replacement",dept_priority_code:"A",dept_priority_rank:2,days_overdue:7,safety_critical_flag:1,requested_duration_min:180,min_viable_duration_min:150,earliest_start_date:"2026-09-14",latest_finish_date:"2026-09-18",request_status:"PENDING",joint_dept_required:null}
];

export function Requests(){const [items,setItems]=useState(demo);const [q,setQ]=useState("");useEffect(()=>{getRequests().then(setItems).catch(()=>{});},[]);const filtered=items.filter(x=>JSON.stringify(x).toLowerCase().includes(q.toLowerCase()));return <div className="page"><section className="page-title"><div><span className="eyebrow">INTEGRATED DEMAND</span><h1>Maintenance Requests</h1><p>Unified requests from Engineering, S&T and TRD.</p></div></section><div className="toolbar panel"><div className="search"><Search size={17}/><input placeholder="Search request, asset or activity" value={q} onChange={e=>setQ(e.target.value)}/></div><button className="secondary-button"><Filter size={16}/> Filters</button></div><section className="panel"><div className="data-table"><div className="data-head"><span>Request</span><span>Department</span><span>Asset</span><span>Activity</span><span>Priority</span><span>Due</span><span>Status</span></div>{filtered.map(x=><div className="data-row" key={x.req_uid}><strong>{x.req_uid}</strong><span><b className="dept-pill">{x.dept}</b></span><span>{x.asset_id}</span><span>{x.activity_desc}</span><span className={x.dept_priority_rank<=2?"priority critical":"priority high"}>{x.dept_priority_code}</span><span>{x.days_overdue>0?<em>{x.days_overdue}d overdue</em>:"Within window"}</span><span><i className="status-dot"/> {x.request_status}</span></div>)}</div></section></div>}
